services:
  - type: web
    name: nexstock-frontend
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: ./build
    envVars:
      - key: REACT_APP_API_URL
        value: https://nexstock-backend.onrender.com/api # Bu URL'i backend'i deploy ettikten sonra g√ºncelleyin
